### ISSUE TITLE
 curriculum-react-redux 

### ISSUE THREAD

**Issue by L2oukmane** [L2oukmane/Space-Travelers-Hub#50]
#### Team Members: 2

**Comment by KDlamini** [comment]
### Hi @L2oukmane, @evans22j 🙋‍♀️,  

Great job so far.
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Required Changes ♻️
 
- Please assign a teammate to each task. Be sure to assign tasks equally, both team members must have a similar sum of points after all tasks are assigned. For group tasks, your can either assign both team members to each group task or individually.

![image](https://user-images.githubusercontent.com/38088818/169102420-66e42bd2-9038-4ed5-92f7-99759b3f0a5a.png)


Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BrianSammit** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello @L2oukmane and @evans22j , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
